{%set name = "py4j" %}
{%set version = "0.10.3" %}
{%set hash_type = "sha256" %}
{%set hash_val = "3c7c523f72fc2a591da4762b2606bad769585e6b1128c6538d76224d3ff17265" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - py4j
    - py4j.tests

about:
  home: http://py4j.sourceforge.net/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Enables Python programs to dynamically access arbitrary Java objects'

extra:
  recipe-maintainers:
    - pmlandwehr
