travis:
  secure:
    BINSTAR_TOKEN: c0urNXTS9mrcbgOucHXBHXTmaLcIcnjc4ar166fgJntmSnDCXSJYoDgvb2NWYeO4217a9qX50NQYWljYH1+MIHIHyyPZfdBMU4GqCBZqKVDbPswKNeHGNWMQqnocLzUO96IW54cCkT6c6izWpu9KmlpMR/U/ShNLJU2U2YaFOK6X28lpM3mRX9T5VY7VKQTQSLxMmB2wi+l/A2HtlLljiqmLBtMg3GIBqdXqMJJY/3SSxi8Q8fouLiiRSqJr1zvR4XNNbEBVKBchDGJzEez/ztt4oxSUiI8g6EcFX0faHy7N4dWAHLG402DU8G8LONeRVH1OkSLG42iE2Y68vCBUoLt8+zilWvCB9CgnQcyIqhUfsZVsoGmfLOgnb7QKh9riyr11YB6/Lmhjswz/6wCkWC+lfcTjSrUJvZ0G/W0VHP2+PTLPe/0Y8f0Zp9aS/xPg4HShFiRQ8LDpxQUP1a2qH6OH86kaeW/Nl54yr4M68e/IElaF6ODug4dheji69LX/ogav/FPcRlBfnL99EjMQG5p5oFNP/xfc5Yk+okpGZIMt4HecVy1sQbvqQqb6Orv0qh7m7RtusIIG4lAfzNQo/Gf0BDmtmA0b6O0EmPf69JXZWZGeLA+8wPvjMvv38wW+qiUv4q0wTk8t+fMO26RF1PQsgPKdXtwQchWs0muwulQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
