travis:
  secure:
    BINSTAR_TOKEN: NZHW/X2+7tXtA74WewzB2YXlIiZC6Ga84TjIfJ56ECDI/C9GiijUTPVpFA7zOMBIAHsW1ZH0iUH/NQXEDbBkeBr/kz2IApVvMAmnXO8yUH9Obcql8FDwLnFFoc2s/Aiijn6SEXYhxMyQyd8z3LUCHVkep6xAsrSkWCj5Vlwe12aLp4j3T1JyJBpZC/OKo2sfuP8CDON0C5SRcZf+qQW79OlAY8/tyeLtHBgMv59MKqYCX1gl+KF1aX9tn0O1DA/IdkthpwbMOT7tchLIPVDqKnAdrwWoTRup/6lD5kKGdL+d2ftuHnKJEYgnAtywcnJXF3b8NlrgIgJA8QXTLa5tbZOApBsdl/2pRDb2Ur/g0np8KTD+72HTFDgtnd0cMLLIawDrY2mi2aoiQ3+rubn+93SkSOFb+QOmMi7zaXKW3z2rt9Ato17DbgYduYyBlMe8ypU47qZV6d8X4d7ks++XiTHLdFGWFeIno6jFKlHAFUe++E2yp4epiipy33wRBjPeRBZcNPp3mGvv3o8U2S2Vj3v2yuvPXfQdNfwsxgx38nWGw1urouscHMTO16qF3G5hVZKTI/ttLEf3QybDexJTEAFF85g5hbIfNa1S6Roovffw+zbO86TtTGpEG1hR1Ed2EZPhV1KjW6OFhOkqRi24N8FASLp6GVf76AfczBNyqMY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
