travis:
  secure:
    BINSTAR_TOKEN: QzP0+wFFAogtoC6ZCNru8a52gMRpaEAtZbKzx/fjBtHfZ82vFxm0Wz4PMa63d/Gfa7E7bDMYqsBCVRnmEOmckvsYP+qiQ8+9agP+VqW1GYldW4QCrcJI+/+eaW89yUfxgqmoE7dkVu+tKkLfH8MqmeCzd42ISLMl/SRd8eTbXoSZHjMKRFj6IvDlbMGwuJZmGFWvM6LKc3IspJKfmGiiLLPlqhoMM3GlsDXFKxaDfwFYHrrEBV4ClKt1ZEOCjfVJj3O2RB7Mz/R5SWnNW8e1I+hXvyZ3+QxBiUpN1Bsx3mpZghC5O6Zqbyko/9jMGAnhhwJokkPaKd0qRYeDfpvq85BLoYyuPBXnig34LQUh0wPrb02KHX7r5ZzneshyMB6w8F7wVcJANcQVG2+dLhrjIZ0stln3I4yTCkjioww928zbXQEtFwVEo8xpGNy0S0DvCu8KqAkD3foS6mvnaFWt1wYgOSpFEA1AdPDX034AWXyRrUVimqFNFY2GfhAVrZRDUFmrkToIpGPdinbLDhCZL5C07pvjsHenI4S8TLi3EnzF7MbzlzdV9qhll/w1E3cfj5QscIOSgcZ58NK0QClVAxgSug9xtBEWZZK4YeQsttGbqp/+DFeqbVA1uKEq93DdtCLA78i3ekpjWujQ26WIHF9J82r/ssZE7Kkr6MPobgo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
